# looks in the templates/job_board folder

INDEX_PAGE = "job_board/index.html"
LOGIN_TYPE_PAGE = "job_board/login_type.html"
LOGIN_PAGE = "job_board/login.html"
LOGIN_SUCCESS_PAGE = "job_board/login_success.html"
LOGOUT_PAGE = "job_board/logout.html"
ADMIN_HOMEPAGE = "job_board/admin_homepage.html"
STUDENT_HOMEPAGE = "job_board/student_homepage.html"
EMPLOYER_HOMEPAGE = "job_board/employer_homepage.html"
ADMIN_MANAGE_POSTS_PAGE = "job_board/manage_posts.html"
ADMIN_MANAGE_ACCOUNTS_PAGE = "job_board/manage_accounts.html"
ADMIN_VIEW_ACCOUNT_PAGE = "job_board/view_account.html"
SEARCH_POSTS_PAGE = "job_board/search_posts.html"
VIEW_POST_PAGE = "job_board/view_post.html"
CREATE_POST_PAGE = "job_board/create_post.html"
POST_SUBMITTED_PAGE = "job_board/post_submitted.html"
EMPLOYER_VIEW_POSTS_PAGE = "job_board/employer_posts.html"
