# Example: localhost:8000/job_board/login

INDEX = ""
LOGIN_TYPE = "/job_board/login-type/"
LOGIN = "/job_board/login/"
LOGIN_SUCCESS = "/job_board/login/login-success/"
LOGOUT = "/job_board/logout/"
ADMIN_HOME = "/job_board/admin/home/"
STUDENT_HOME = "/job_board/student/home/"
EMPLOYER_HOME = "/job_board/employer/home/"
ADMIN_MANAGE_POSTS = "/job_board/admin/manage-posts/"
ADMIN_MANAGE_ACCOUNTS = "/job_board/admin/manage-accounts/"
ADMIN_VIEW_ACCOUNT = "/job_board/admin/view-account/"
SEARCH_POSTS = "/job_board/student/search-posts/"
VIEW_POST = "/job_board/student/view-post"
CREATE_POST = "/job_board/employer/create-post/"
POST_SUBMITTED = "/job_board/employer/create-post/post-submitted/"
EMPLOYER_VIEW_POSTS = "/job_board/employer/view-posts/"
